language: node_js

node_js:
  - "stable"

branches:
  only:
    - main

cache: yarn

install:
  - yarn global add lerna jest
  - lerna bootstrap

jobs:
  include:
    - stage: bootstrap
      script: yarn bootstrap
    - stage: unit tests (api + app)
      script: yarn test
    - stage: build app
      script: yarn build
    - stage: deploy (api)
      script: skip
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: $HEROKU_APP_NAME
        strategy: git
    - stage: deploy (app)
      script: skip
      deploy:
        provider: pages
        local_dir: ./packages/app/build
        github_token: $GITHUB_TOKEN
